DROP TABLE detalle_compra;
DROP TABLE compras;
DROP TABLE productos;
DROP TABLE usuarios;
DROP PROCEDURE comprarProductos;
DROP PROCEDURE selectCompras;
DROP PROCEDURE selectDetallesCompra;
DROP PROCEDURE selectProducto;
DROP PROCEDURE selectProductos;